#!/bin/bash

echo '{'
			  echo '"group": "#Home",'
			     echo  '"subgroups": ['
			       echo  '{'
					    echo '"title": "Hardware",'
						    echo ' "content": ['
						          echo '{"type": "plain","text": "Remplissage Gitlab", "value": "ok"},'
								         echo '{"type": "plain","text": "Remplissage Home", "color":"blue","value": "coucou"},'
										 	 echo '{"type": "plain", "text": "Memoire vive", "color":"blue","value": "hello","endline": ""}'
											      echo ']'
											        echo '}'
												  echo ']'
											  echo '}'
